name: LastLog
version: 2.0.0
api-version: 1.21
description: Show listing of last logged in players
main: edu.self.startux.lastLog.LastLogPlugin
author: StarTux
permissions:
  lastlog.*:
    description: "get all permission nodes"
    default: false
    children:
      lastlog.lastlog: true
      lastlog.firstlog: true
      lastlog.loginfo: true
      lastlog.notify: true
      lastlog.self: true
  lastlog.lastlog:
    description: "execute the /lastlog command"
    default: op
  lastlog.firstlog:
    description: "execute the /firstlog command"
    default: op
  lastlog.loginfo:
    description: "execute the /loginfo command"
    default: op
  lastlog.notify:
    description: "get notified when a new player joins"
    default: op
  lastlog.self:
    description: "query information about yourself"
    default: op
